### ISSUE TITLE
Double * in the label when field is required

### ISSUE THREAD

**Issue by CecileBr** [WordPressUtilities/wpucontactforms#1]
Hi @Darklg!

I noticed that the `*`is doubled when a field is registered as required like below.
```php
'contact_firstname' => array(
      'label' => 'Prénom',
      'autofill' => 'first_name',
       'required' => 1
),
```

The result is like this.
<img width="628" alt="Capture d’écran 2022-04-18 à 14 23 36" src="https://user-images.githubusercontent.com/26202228/163814868-d54d8bff-dfbd-4b0a-83ed-2c5a08aa1a11.png">

The `*` is added via the default setting `label_text_required` and the css below.
```css
.wpucontactforms-form-wrapper [data-required="true"] > label:not(.label-checkbox):after {
    content: '*';
}
```

Is that the normal behavior ?

Thanks!
